### ISSUE TITLE
Recovering actual mutated file?

### ISSUE THREAD

**Issue by iamgroot42** [iboutsikas/montemutacon#1]
Hey,

First off- thanks for providing an official implementation, along with proper documentation. The codebase was fairly straightforward to understand and set up!

I just had a couple of questions about running it on actual PE files, and I would greatly appreciate your help.

- Can you please provide a snippet for extracting all the features (like `imported_funcs`, `entry`, etc.) from a given PE file? I understand you used a subset of LIEF features like EMBER, but I'm not exactly sure how to get these exact ones, or if any processing is required.
- The mutator has a `recover_path` function, but I'm not quite sure how to get actual mutations. How can I get the actual mutated PE file as output for a given input PE file?

**Comment by iboutsikas** [comment]
Hello,

The features were taken from the EMBER data set itself with some string concatenation so we could get names like `dll::function` so we can also have the relationship between the dll and the function. In essence for each sample in the EMBER data set our code did something like this, where curr_instance is an element that would be inserted in our mongo db database:

```py
drop columns ['md5', 'appeared', 'avclass', 'histogram', 'byteentropy', 'datadirectories'] 

for row in samples:
    # label, unlabeled skip the instance
    if row.label == -1:
        continue
    curr_instance['label'] = int(row.label)

    # strings
    curr_instance['strings_entropy'] = float(row.strings['entropy'])
    curr_instance['num_strings'] = int(row.strings['numstrings'])

    # general
    curr_instance['file_size'] = int(row.general['size'])
    curr_instance['num_exports'] = int(row.general['exports'])
    curr_instance['num_imports'] = int(row.general['imports'])
    curr_instance['has_debug'] = int(row.general['has_debug'])
    curr_instance['has_signature'] = int(row.general['has_signature'])

    # header
    curr_instance['timestamp'] = int(row.header['coff']['timestamp'])
    curr_instance['sizeof_code'] = int(row.header['optional']['sizeof_code'])

    # sections
    curr_instance['entry'] = row.section['entry'].strip()
    curr_instance['num_sections'] = len(row.section['sections'])

    section_names = list()
    for sec in row.section['sections']:
        section_names.append(sec['name'])
    curr_instance['section_names'] = section_names

    section_sizes = list()
    for sec in row.section['sections']:
        section_sizes.append(int(sec['size']))
    curr_instance['section_sizes'] = section_sizes

    section_entopies = list()
    for sec in row.section['sections']:
        section_entopies.append(float(sec['entropy']))
    curr_instance['section_entropies'] = section_entopies


    # imports
    curr_instance['imported_libs'] = list(row.imports.keys())

    import_functions=list()
    import_lib_func = list()
    for key, value in row.imports.items():
        import_functions.append(value)
        for ff in value:
            import_lib_func.append(key+':'+ff)
        

    curr_instance['imported_funcs'] = list(itertools.chain(*import_functions))
    curr_instance['import_lib_func'] = import_lib_func
```

We are not directly producing modified PEs. `recover_path` will give you which mutations it applied to the metadata that we got from the dataset. So this will tell you that it "Added 1 string" and "Added one section", but if you want to produce an executable that actually has those modifications, that's up to you.
